services:
  - type: web
    name: whisprr-server
    env: node
    buildCommand: cd server && npm install
    startCommand: cd server && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3001
      - key: CORS_ORIGIN
        value: https://firebrick-turtle-743776.hostingersite.com
    healthCheckPath: /
    autoDeploy: true
    plan: free
