export const clerkAppearance = {
  elements: {
    formButtonPrimary:
      "bg-primary-600 hover:bg-primary-700 text-sm normal-case",
    card: "bg-dark-200 border border-dark-300",
    headerTitle: "text-white",
    headerSubtitle: "text-gray-400",
    socialButtonsBlockButton:
      "bg-dark-300 border border-dark-400 text-white hover:bg-dark-400",
    formFieldInput:
      "bg-dark-300 border border-dark-400 text-white focus:border-primary-500",
    formFieldLabel: "text-gray-400",
    footerActionLink: "text-primary-500 hover:text-primary-400",
    formFieldAction: "text-primary-500 hover:text-primary-400",
    identityPreviewEditButton: "text-primary-500 hover:text-primary-400",
    formFieldInputShowPasswordButton: "text-gray-400 hover:text-gray-300",
    alertText: "text-gray-400",
    alert: "bg-dark-300 border border-dark-400",
    formFieldWarningText: "text-yellow-500",
    formFieldSuccessText: "text-green-500",
    dividerLine: "bg-dark-300",
    dividerText: "text-gray-400",
    formFieldHintText: "text-gray-500",
    otpCodeFieldInput:
      "bg-dark-300 border border-dark-400 text-white focus:border-primary-500",
    footerAction: "text-gray-400",
    footerActionLink: "text-primary-500 hover:text-primary-400",
    identityPreviewText: "text-gray-400",
    formResendCodeLink: "text-primary-500 hover:text-primary-400",
    navbar: "bg-dark-200 border-b border-dark-300",
    navbarMobileMenuButton: "text-gray-400 hover:text-gray-300",
    navbarBackButton: "text-gray-400 hover:text-gray-300",
    navbarBrand: "text-white",
    navbarUserButton: "text-gray-400 hover:text-gray-300",
    navbarUserButtonAvatar: "bg-dark-300",
    navbarUserButtonPopoverCard: "bg-dark-200 border border-dark-300",
    navbarUserButtonPopoverActionButton: "text-gray-200 hover:bg-dark-300",
    navbarUserButtonPopoverFooter: "border-t border-dark-300",
  },
  layout: {
    socialButtonsPlacement: "bottom",
    socialButtonsVariant: "blockButton",
    shimmer: "bg-dark-300",
    logoPlacement: "inside",
    logoImageUrl: "/logo.png",
    privacyPageUrl: "/privacy",
    termsPageUrl: "/terms",
  },
  variables: {
    colorPrimary: "#0ea5e9",
    colorText: "#ffffff",
    colorTextSecondary: "#9ca3af",
    colorBackground: "#1E1E1E",
    colorInputBackground: "#2D2D2D",
    colorInputText: "#ffffff",
    colorSuccess: "#22c55e",
    colorDanger: "#ef4444",
    colorWarning: "#f59e0b",
  },
};
